sudo: required
language: cpp

matrix:
  include:
    - os: osx
      compiler: clang

    - os: linux
      dist: bionic
      compiler: gcc
      env:
        - COMPILER=g++
        - GCOV=gcov

    - os: linux
      dist: bionic
      compiler: clang
      env:
        - COMPILER=clang++

cache:
    apt: true
    ccache: true
    directories:
    - $HOME/.wheelhouse

# Don't omit tags (default is git --depth=50).
git:
  depth: 9999999

before_install:
  - utils/travis/before-install-${TRAVIS_OS_NAME}.sh

install:
  - utils/travis/install-${TRAVIS_OS_NAME}.sh

script:
  - utils/travis/script-${TRAVIS_OS_NAME}.sh

after_success:
  - utils/travis/after_success-${TRAVIS_OS_NAME}.sh

deploy:
  provider: releases
  api_key:
    secure: Vax27ifQsc8SlTsLYVbxVJANDAxDroegN6nOPXCN1MLaoh4W2DQ/iGGx+waIOSYig8Sh+AUz2JhCFuMLMVqwFoWY2rxNPBrxhTBjm3aDhylbB+mRECnbInNb0kS3qv4lNDN6lHD4B6K01FWUUiHX14s2JQx4ut+KuwMxxhxyO4Y=
  file: 'build/*.dmg'
  file_glob: true
  skip_cleanup: true
  overwrite: true
  on:
    condition: "$TRAVIS_OS_NAME = osx"
    tags: true
    all_branches: true
    repo: hluk/CopyQ
